DROP TABLE IF EXISTS prestasi;

CREATE TABLE IF NOT EXISTS prestasi (
    id BIGSERIAL PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    nama_prestasi VARCHAR(255) NOT NULL,
    juara VARCHAR(50) NOT NULL
);